# Generated by Django 5.1.2 on 2024-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_task', '0005_alter_analyzertask_task_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzertask',
            name='helper_instruction',
            field=models.TextField(blank=True, default=('subject description', '5 descriptive keywords', 'camera type', 'camera lens type', 'time of day', 'style of photograph', 'type of film'), null=True),
        ),
    ]
