# Generated by Django 5.1.2 on 2024-10-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_task', '0007_alter_analyzertask_audio_file_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzertask',
            name='audio_file_language',
            field=models.TextField(blank=True, choices=[('uk', 'uk'), ('en', 'en'), ('ru', 'ru')], max_length=20, null=True),
        ),
    ]
